version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=pastgres
      - POSTGRES_PASSWORD=supersecretpassword

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A MajiSafi worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env

volumes:
  postgres_data:
