# Generated by Django 4.1.2 on 2022-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='bottle_size',
            field=models.CharField(max_length=50),
        ),
    ]
