# Generated by Django 4.1.2 on 2022-11-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('-created_at',)},
        ),
    ]
