# Generated by Django 4.2.5 on 2024-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle_size',
            field=models.CharField(choices=[('250ML', '250 Milliliters'), ('500ML', '500 Milliliters'), ('300ML', '300 Milliliters'), ('1L', '1 Liter'), ('1.5L', '1.5 Liters'), ('2L', '2 Liters'), ('5L', '5 Liters'), ('10L', '10 Liters'), ('20L', '20 Liters')], max_length=50),
        ),
    ]
