# Generated by Django 4.2.5 on 2024-12-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_product_bottle_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
