# Generated by Django 4.1.2 on 2022-11-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='bottle_size',
        ),
    ]
