# Generated by Django 4.2.5 on 2025-01-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle_size',
            field=models.CharField(choices=[('250ML', '250 Millilitres'), ('500ML', '500 Millilitres'), ('300ML', '300 Millilitres'), ('1L', '1 Litre'), ('1.5L', '1.5 Litres'), ('2L', '2 Litres'), ('5L', '5 Litres'), ('10L', '10 Litres'), ('20L', '20 Litres')], max_length=50),
        ),
    ]
