# Generated by Django 4.1.2 on 2022-11-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('services', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
    ]
