# Generated by Django 4.2.5 on 2025-02-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_product_bottle_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['bottle_size']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('water_type',)},
        ),
    ]
