# Generated by Django 4.1.2 on 2022-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
