# Generated by Django 4.1.2 on 2022-11-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
