# Generated by Django 4.1.3 on 2022-12-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_openinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ('day', '-from_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('supplier', 'day', 'from_hour', 'to_hour')},
        ),
    ]
