# Generated by Django 4.1.3 on 2022-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_openinghour_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ('day', 'from_hour')},
        ),
    ]
