# Generated by Django 4.1.3 on 2022-12-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='town',
        ),
    ]
