# Generated by Django 4.1.3 on 2023-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_openinghour_options'),
        ('orders', '0006_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
